### ISSUE TITLE
Missing AddPolicies to implement the persist.BatchAdapter interface

### ISSUE THREAD

**Issue by dwhu** [Blank-Xu/sql-adapter#1]
I was running a new casbin instance with the following setup:

```
func New(modelPath string, db *sql.DB) (*Authz, CloseFn, error) {
	a, err := sqladapter.NewAdapter(db, "mysql", "AuthzRules")
	if err != nil {
		return nil, nil, fmt.Errorf("NewAdapter(): %v", err)
	}

	e, err := casbin.NewSyncedEnforcer(modelPath, a)
	if err != nil {
		return nil, nil, fmt.Errorf("NewSyncedEnforcer(): %v", err)
	}

	// Load the policy from DB.
	if err = e.LoadPolicy(); err != nil {
		return nil, nil, fmt.Errorf("LoadPolicy failed, err: %v", err)
	}

	e.StartAutoLoadPolicy(reloadDuration)
	return &Authz{e: e}, func() {
		e.StopAutoLoadPolicy()
	}, nil
}
```

When I booted my server, I got the following error:

```
interface conversion: *sqladapter.Adapter is not persist.BatchAdapter: missing method AddPolicies
```

Looks like the implementation is a bit behind casbin's currently. I'm happy to pick this up if you're not able to get to it soon.

**Comment by Blank-Xu** [comment]
Casbin has added some new functions, I'll fix it.

**Comment by Blank-Xu** [comment]
Please checkout the new branch `future`.

I have upgrade `Casbin` package version to v2.33 and added the missed functions,
but didn't tested enough.

Would you mind to help me to find out the bugs?

**Comment by Blank-Xu** [comment]
fixed.

**Comment by hsluoyz** [comment]
@dwhu fixed in: https://github.com/Blank-Xu/sql-adapter/commit/0bdd0d548758d38887a72a3b484212ac499b36cf , use latest release: https://github.com/Blank-Xu/sql-adapter/releases

**Comment by dwhu** [comment]
Finally got some time to upgrade and test it out. Confirmed it works! Thanks everyone
